global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orchestrator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['agent_orchestrator_app:28000']

  - job_name: 'echo_agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['agent_echo_server:28001']

  - job_name: 'langchain_agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['agent_langchain_server:28003']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['agent_cadvisor:8080']
